---
title: "Data Wrangling-Asthma Rates"
author: "Dwiti Bagadia and Yue Zhang"
date: "2023-04-18"
output: pdf_document
---

```{r setup, include = FALSE}
#This code chunk will tidy your knit PDF files, wrapping long code lines
#For it to work, the "formatR" package needs to be installed
#install.packages('formatR')
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=40), tidy=TRUE)

```

## OVERVIEW

This R Markdown file aims to wrangle the data of New York State residents' asthma rates per 10,000 that age from 0 to 17 from 2018 to 2020.

## Set working directory and load packages
```{r packages, message = FALSE}
library(tidyverse)
library(lubridate)
library(dplyr)
```

## Load data
```{r data, message = FALSE}
setwd("E:/MCRP/Spring2023/BagadiaZhang_ENV872_EDA_FinalProject")
getwd()
NY_Asthma = read.csv("./Data/RawData/AD-CountyMostRecentYearData.csv")

```

## Clean the original dataset
```{r clean data, message = FALSE}
NY_Asthma_Clean = NY_Asthma[-c(1,2), c(1,5:7)]
colnames(NY_Asthma_Clean) = c("County", "Indicator", "EDVisits", "AvePop")

```

## Calculate emergency visit rate per 10,000
```{r, message = FALSE}
NY_Asthma_Clean$EDVisits = gsub(",","",NY_Asthma_Clean$EDVisits)
NY_Asthma_Clean$AvePop = gsub(",","",NY_Asthma_Clean$AvePop)
NY_Asthma_Clean = NY_Asthma_Clean %>% 
  filter(Indicator == "Asthma emergency department visit rate per 10,000 - aged 0-17 years")  %>% 
  mutate("Rate" = as.numeric(EDVisits)*10000/as.numeric(AvePop)) %>% 
  select(County, Rate)

```

## Save NY data
```{r data save, message = FALSE}
write.csv(NY_Asthma_Clean, "./Data/ProcessedData/NY_processed1.csv", row.names = FALSE)


```