---
title: "Data Wrangling_Demographic"
author: "Dwiti Bagadia and Yue Zhang"
date: "2023-04-26"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
#This code chunk will tidy your knit PDF files, wrapping long code lines
#For it to work, the "formatR" package needs to be installed
#install.packages('formatR')
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=40), tidy=TRUE)

```

## OVERVIEW

This R Markdown file aims to wrangle the demographic data of New York State by census track from 2016 to 2022.

## Set working directory and load packages
```{r packages, message = FALSE}
setwd("E:/MCRP/Spring2023/BagadiaZhang_ENV872_EDA_FinalProject")
getwd()
library(tidyverse)
library(lubridate)
library(dplyr)
```

## Load data
```{r data, message = FALSE}
NY_Demographic = read.csv(
  "../BagadiaZhang_ENV872_EDA_FinalProject/Data/RawData/R13363308_SL140.csv"
)

```

## Clean the original dataset
```{r clean data, message = FALSE}
NY_Demographic = NY_Demographic[-1,]
a = strsplit(NY_Demographic$Qualifying.Name, ",")
a = unlist(a)
str(a)
NY_Demographic$Census  = a[seq(1,16233,3)]
NY_Demographic$COUNTY = a[seq(2,16233,3)]
NY_Demographic$STATE = a[seq(3,16233,3)]
NY_Demographic_clean = NY_Demographic[,c(72, 71, 48, 58, 60, 63:69)]
colnames(NY_Demographic_clean) = c("State", "County", "CountyFIPS", "TotalPop", "LandArea_SqMile", "White", "Black", "AmeIndian", "Asian", "Hawaiian", "Other", "TwoOrMore")

```

## Calculate the non white population density.
```{r, message = FALSE}
NY_Demographic_clean = NY_Demographic_clean %>% mutate("NonWhiteDens" = (as.numeric(TotalPop) - as.numeric(White))/as.numeric(LandArea_SqMile)) %>% select("County", "CountyFIPS", "NonWhiteDens")

```

## Save data
```{r data save, message = FALSE}
write.csv(NY_Demographic_clean, "./Data/ProcessedData/NY_Demographic_processed.csv", row.names = FALSE)

```