---
title: "Data Wrangling_Air Quality"
author: "Dwiti Bagadia and Yue Zhang"
date: "2023-04-27"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
#This code chunk will tidy your knit PDF files, wrapping long code lines
#For it to work, the "formatR" package needs to be installed
#install.packages('formatR')
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=40), tidy=TRUE)

```

## OVERVIEW

This R Markdown file aims to wrangle the data of New York State air quality by county in 2020.

## Set working directory and load packages
```{r packages, message = FALSE}
setwd("E:/MCRP/Spring2023/BagadiaZhang_ENV872_EDA_FinalProject")
getwd()
library(tidyverse)
library(lubridate)
library(dplyr)
```

## Load data
```{r data, message = FALSE}
US_AQ = read.csv("./Data/RawData/annual_aqi_by_county_2020.csv")

```

## Select NY data
```{r NY data, message = FALSE}
NY_AQ = subset(US_AQ, State == "New York")

```

## Clean NY data and calculate days with bad air quality rate
```{r clean NY data, message = FALSE}
NY_AQ_clean = NY_AQ %>% mutate("BadDaysRate" = (as.numeric(Days.with.AQI) - as.numeric(Good.Days))/as.numeric(Days.with.AQI)) %>% select(County, BadDaysRate)

```

## Save NYC AQ data
```{r save data, message = FALSE}
write.csv(NY_AQ_clean, "./Data/ProcessedData/NY_AQ_processed.csv", row.names = FALSE)

```