---
title: "Data Exoploration_Asthma and Demographic"
author: "Dwiti Bagadia and Yue Zhang"
date: "2023-05-02"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
#This code chunk will tidy your knit PDF files, wrapping long code lines
#For it to work, the "formatR" package needs to be installed
#install.packages('formatR')
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=40), tidy=TRUE)

```

## OVERVIEW

This R Markdown file aims to explore asthma rate and demographic data.

## Set working directory and load packages
```{r packages, message = FALSE}
setwd("E:/MCRP/Spring2023/BagadiaZhang_ENV872_EDA_FinalProject")
getwd()
library(tidyverse)
library(lubridate)
library(dplyr)
library(agricolae)
library(ggthemes)

```

## Load data and set plot themes
```{r data, message = FALSE}
NY_Asthma_processed = read.csv("./Data/ProcessedData/NY_Asthma_processed1.csv")
NY_Demographic_processed = read.csv("./Data/ProcessedData/NY_Demographic_processed1.csv")
mytheme = theme_clean(base_size = 12) + 
  theme(axis.text = element_text(color = "black"), legend.position = "right", axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 0.5), plot.title = element_text(size = 12))
theme_set(mytheme)
```

## Join the asthma data and non-White population density data together
```{r join, message = FALSE}
NY_Asthma_Demo_join = left_join(NY_Demographic_processed, NY_Asthma_processed, by = "County")

```

## Visualize the relationship of asthma rate by non-White population density with a scatter plot
```{r scatter plot, message = FALSE}
AsthmaDemo.points = ggplot(NY_Asthma_Demo_join, aes(y = VisitRate, x = NonWhiteDens)) + 
  geom_point(aes(color = County)) + 
  geom_smooth(method = "lm") + 
  labs(y = "Emergency Visit Rate (per 10k)", x = "Non-White Population Density (per sq.mile)")
print(AsthmaDemo.points)

```