---
title: "Data Wrangling_Asthma"
author: "Dwiti Bagadia and Yue Zhang"
date: "2023-04-25"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
#This code chunk will tidy your knit PDF files, wrapping long code lines
#For it to work, the "formatR" package needs to be installed
#install.packages('formatR')
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=40), tidy=TRUE)

```

## OVERVIEW

This R Markdown file aims to wrangle the data of New York State's model-based estimate for crude prevalence of current asthma among adults aged >=18 years, 2020, which is the number of cases per 100,000 population at risk..

## Set working directory and load packages
```{r packages, message = FALSE}
library(tidyverse)
library(lubridate)
library(dplyr)

```

## Load data
```{r data, message = FALSE}
setwd("E:/MCRP/Spring2023/BagadiaZhang_ENV872_EDA_FinalProject")
getwd()
US_Asthma = read_csv("../BagadiaZhang_ENV872_EDA_FinalProject/Data/RawData/PLACES__Census_Tract_Data__GIS_Friendly_Format___2022_release.csv")

```

## Clean the original dataset
```{r clean data, message = FALSE}
US_Asthma_clean = US_Asthma[,c((2:5),19)]
colnames(US_Asthma_clean) = c("State", "County","CountyFIPS", "TractFIPS", "AsthmaRate")

```

## Select New York data
```{r NY data, message = FALSE}
NY_Asthma = filter(US_Asthma_clean, State == "New York")

```

## Save NYC data
```{r NYC data save, message = FALSE}
write.csv(NY_Asthma, "./Data/ProcessedData/NY_Asthma", row.names = FALSE)


```